"""Turn a directory of captured frames into a demo sprite plus its CSS.

    python scripts/build_demo_sprite.py pellet-close ~/frames/pel_close2 --duration 4.2

Writes three files and nothing else:

    public/rig/<id>.webp          the frame grid
    public/rig/<id>-poster.webp   the at-rest image (--poster-frame)
    src/demo-<id>.css             poster rule, background-size, keyframes

--poster-frame picks which captured frame becomes the poster: "first"
(the default), "last", or a 0-based index. Choose it deliberately. The
poster is not just a placeholder - the generated CSS attaches the sheet
only inside prefers-reduced-motion: no-preference, so under reduce the
poster is the entire rendering of the figure. A build-up sequence that
posters frame 0 shows a visitor with motion reduced a pile of parts
where the assembled thing belongs; it wants "last". A cyclic demo whose
last frame is mid-motion wants "first".

background-size and the keyframes are emitted together, in the generated
file, because that pairing is the one thing that silently desyncs: change
the frame count without regenerating both and every frame lands off-grid.
Do not lift either value into src/spa.css.

The grid is chosen as the smallest square that holds the frames, and the
frame count must fill it exactly - a partial last row would leave blank
cells that the keyframes would still step through. Capture a square
number of frames (49, 64, 81, 100).

Frames and resolution come out of one budget: the sheet is frames x cell
squared, and it is decoded whole. Decide the split against the slot the
figure ships into - a project page gives .rig-figure up to 738px and
.demo-figure 640px - and aim for about 1 source pixel per CSS pixel. This
script prints that ratio and warns past BUDGET_SIDE. Section 8 of
docs/fusion-animation-pipeline.md has the measured slots and the tradeoff.
"""

import argparse
import math
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# WebP's own hard limit, not a GPU texture limit: libwebp stores dimensions in
# 14 bits and raises "encoding error 5" at exactly 16384. The guard here used to
# read 16384, which let that one case through to fail inside the encoder with a
# worse message.
MAX_SIDE = 16383

# The real ceiling is well below MAX_SIDE and it is memory, not bytes. A sheet
# is decoded to RGBA whole - 4 bytes a pixel - and held for as long as the
# figure is live, so 6400px a side is ~41 megapixels and ~164MB resident. File
# size scales as roughly pixels^0.74 and is the forgiving half; decoded size is
# linear and is not. Over the budget is a warning rather than an error because
# buildup (6600, 174MB) already exceeds it and is not being re-shot today.
# See "The budget is frames x cell^2" in docs/fusion-animation-pipeline.md.
BUDGET_SIDE = 6400

HEADER = """/* GENERATED by scripts/build_demo_sprite.py. Do not hand-edit.
   demo "{id}": {n} frames, {c}x{r} grid, cell {px}x{px}.
   Poster, background-size and keyframes all live here so a re-capture
   with a different grid cannot desync them from the stylesheet.

   The sprite is attached ONLY inside prefers-reduced-motion:
   no-preference. Under reduce, .is-playing therefore keeps the poster
   instead of showing the whole grid shrunk to fit. */

.demo-figure[data-demo="{id}"] {{
  background-image: url("/rig/{id}-poster.webp");
}}

@media (prefers-reduced-motion: no-preference) {{
  .demo-figure[data-demo="{id}"].is-playing {{
    background-image: url("/rig/{id}.webp");
    background-size: {sx}% {sy}%;
    animation: demo-{id} {dur}s steps(1) 1 both;
  }}
}}

@keyframes demo-{id} {{
"""
SCROLL_HEADER = """/* GENERATED by scripts/build_demo_sprite.py --scroll. Do not hand-edit.
   figure "{id}": {n} frames, {c}x{r} grid, cell {px}x{px}.

   Scroll-scrubbed, not time-based: one step-end stop per frame on a view()
   timeline. Poster, background-size, keyframes and the animation range all
   live here, so a re-capture with a different grid cannot desync them.

   Everything is scoped to [data-figure="{id}"] so several scroll figures can
   coexist; the shared .rig-figure rules in spa.css carry layout only.

   The sheet is attached ONLY inside prefers-reduced-motion: no-preference and
   behind .is-live, which React adds when the case study opens. A closed
   <details> does not stop a CSS background fetch, so that class is what makes
   the payload opt-in. */

.rig-figure[data-figure="{id}"] {{
  background-image: url("/rig/{id}-poster.webp");
}}

@media (prefers-reduced-motion: no-preference) {{
  @supports (animation-timeline: view()) {{
    .rig-figure[data-figure="{id}"].is-live {{
      background-image: url("/rig/{id}.webp");
      background-size: {sx}% {sy}%;
      background-position: 0% 0%;
      animation: rig-{id} step-end both;
      animation-timeline: view();
      /* contain is the window where the figure is wholly on screen, inset at
         both ends so the first and last frames get a beat of stillness. */
      animation-range: contain 8% contain 92%;
    }}

    /* contain has no range when the square figure cannot fit the viewport,
       which would hold the scrub on frame 0. */
    @media (max-height: 45rem) {{
      .rig-figure[data-figure="{id}"].is-live {{
        animation-range: cover 32% cover 68%;
      }}
    }}
  }}
}}

@keyframes rig-{id} {{
"""


def poster_index(spec, n, label="--poster-frame"):
    """Resolve a poster-frame spec to a 0-based index into n frames.

    Accepts "first", "last" or a 0-based index, and raises ValueError on
    anything else - including an in-the-wrong-direction index. Clamping
    would be worse than failing: the poster is the whole reduced-motion
    rendering, so a quietly substituted frame ships a wrong picture that
    only a visitor with motion reduced ever sees.
    """
    if spec == "first":
        return 0
    if spec == "last":
        return n - 1
    try:
        i = int(spec)
    except (TypeError, ValueError):
        raise ValueError('%s must be "first", "last" or a frame index, got %r'
                         % (label, spec))
    if not 0 <= i < n:
        raise ValueError("%s %d is out of range: %d frames, valid 0-%d"
                         % (label, i, n, n - 1))
    return i


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("demo_id")
    ap.add_argument("frames_dir")
    ap.add_argument("--duration", type=float, default=4.0)
    ap.add_argument("--quality", type=int, default=82)
    ap.add_argument("--poster-frame", default="first", metavar="FRAME",
                    help='which frame becomes the poster: "first" (default), '
                         '"last", or a 0-based frame index. The poster is the '
                         "at-rest image AND the whole rendering under "
                         "prefers-reduced-motion, so a build-up sequence wants "
                         '"last"; a cyclic demo that ends mid-motion wants '
                         '"first".')
    ap.add_argument("--scroll", action="store_true",
                    help="emit scroll-scrubbed src/rig-<id>.css instead of "
                         "the time-based src/demo-<id>.css")
    args = ap.parse_args()

    files = sorted(
        f for f in os.listdir(args.frames_dir) if f.startswith("f") and f.endswith(".png")
    )
    if not files:
        sys.exit("no f*.png frames in " + args.frames_dir)
    n = len(files)
    side = int(round(math.sqrt(n)))
    if side * side != n:
        sys.exit("frame count %d is not a perfect square; capture 49/64/81/100" % n)

    # Resolved before the sheet is composed so a bad index fails in a second
    # rather than after a minute of encoding.
    try:
        poster_i = poster_index(args.poster_frame, n)
    except ValueError as err:
        sys.exit(str(err))

    first = Image.open(os.path.join(args.frames_dir, files[0]))
    px = first.size[0]
    if first.size[0] != first.size[1]:
        sys.exit("frames must be square, got %s" % (first.size,))
    if side * px > MAX_SIDE:
        sys.exit("sheet would be %dpx wide, over WebP's %d limit. Either keep "
                 "this %dpx cell and drop to %d frames, or keep %d frames and "
                 "recapture at %dpx cells. Both are still over the %dpx budget."
                 % (side * px, MAX_SIDE, px, (MAX_SIDE // px) ** 2,
                    n, MAX_SIDE // side, BUDGET_SIDE))

    # Before the encode, which takes a minute at these sizes, so an over-budget
    # sheet is something you can still cancel out of.
    if side * px > BUDGET_SIDE:
        sys.stderr.write(
            "warning: sheet is %dpx (%.0f MPix, ~%.0fMB decoded), over the "
            "%dpx budget. Two ways back under it, and they are alternatives: "
            "keep this %dpx cell and drop to %d frames, or keep %d frames and "
            "recapture at %dpx cells. Prefer the first - an assembly sequence "
            "gives up frames cheaply because the reader steps it one press at "
            "a time, whereas a cycle's frame rate is the content.\n"
            % (side * px, (side * px) ** 2 / 1e6, (side * px) ** 2 * 4 / 1e6,
               BUDGET_SIDE, px, (BUDGET_SIDE // px) ** 2,
               n, BUDGET_SIDE // side))

    sheet = Image.new("RGBA", (side * px, side * px), (0, 0, 0, 0))
    for i, name in enumerate(files):
        im = Image.open(os.path.join(args.frames_dir, name)).convert("RGBA")
        sheet.paste(im, ((i % side) * px, (i // side) * px))

    out_dir = os.path.join(ROOT, "public", "rig")
    os.makedirs(out_dir, exist_ok=True)
    sprite = os.path.join(out_dir, args.demo_id + ".webp")
    poster = os.path.join(out_dir, args.demo_id + "-poster.webp")
    sheet.save(sprite, "WEBP", quality=args.quality, method=6)
    poster_src = (first if poster_i == 0
                  else Image.open(os.path.join(args.frames_dir, files[poster_i])))
    poster_src.convert("RGBA").save(poster, "WEBP", quality=88, method=6)

    step = 100.0 / (side - 1)
    lines = []
    for i in range(n):
        t = 100.0 * i / (n - 1)
        lines.append("  %.4f%% { background-position: %.4f%% %.4f%%; }"
                     % (t, (i % side) * step, (i // side) * step))
    tpl = SCROLL_HEADER if args.scroll else HEADER
    css = tpl.format(id=args.demo_id, n=n, c=side, r=side, px=px,
                     sx=side * 100, sy=side * 100, dur=("%g" % args.duration))
    css += "\n".join(lines) + "\n}\n"
    css_path = os.path.join(
        ROOT, "src", ("rig-%s.css" if args.scroll else "demo-%s.css") % args.demo_id)
    with open(css_path, "w", newline="\n") as f:
        f.write(css)

    print("sprite  %s  %dx%d  %dKB  (%.0f MPix, ~%.0fMB decoded)"
          % (os.path.relpath(sprite, ROOT), side * px, side * px,
             os.path.getsize(sprite) // 1024,
             (side * px) ** 2 / 1e6, (side * px) ** 2 * 4 / 1e6))
    # The number to judge the capture by. A CAD sheet wants to land near 1.0
    # against the slot it ships into; the project page gives .rig-figure up to
    # 738px at a 900-tall viewport and .demo-figure 640px, so those are the
    # divisors that matter. Measured slots are tabulated in section 8 of
    # docs/fusion-animation-pipeline.md.
    print("        %.2f src px / CSS px at a 738px .rig-figure, %.2f at a "
          "640px .demo-figure" % (px / 738.0, px / 640.0))
    print("poster  %s  %dKB  (frame %d of %d, %s)"
          % (os.path.relpath(poster, ROOT), os.path.getsize(poster) // 1024,
             poster_i, n, files[poster_i]))
    print("css     %s  (%s, %d keyframes, background-size %d%%)"
          % (os.path.relpath(css_path, ROOT),
             "scroll-scrubbed" if args.scroll else "%gs timed" % args.duration,
             n, side * 100))


if __name__ == "__main__":
    main()
