"""Turn a directory of captured frames into a demo sprite plus its CSS.

    python scripts/build_demo_sprite.py pellet-close ~/frames/pel_close2 --duration 4.2

Writes three files and nothing else:

    public/rig/<id>.webp          the frame grid
    public/rig/<id>-poster.webp   frame 0, the at-rest image
    src/demo-<id>.css             poster rule, background-size, keyframes

background-size and the keyframes are emitted together, in the generated
file, because that pairing is the one thing that silently desyncs: change
the frame count without regenerating both and every frame lands off-grid.
Do not lift either value into src/spa.css.

The grid is chosen as the smallest square that holds the frames, and the
frame count must fill it exactly - a partial last row would leave blank
cells that the keyframes would still step through. Capture a square
number of frames (49, 64, 81, 100).
"""

import argparse
import math
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAX_TEXTURE = 16384  # WebGL/GPU limit; a wider sheet renders blank on mobile

HEADER = """/* GENERATED by scripts/build_demo_sprite.py. Do not hand-edit.
   demo "{id}": {n} frames, {c}x{r} grid, cell {px}x{px}.
   Poster, background-size and keyframes all live here so a re-capture
   with a different grid cannot desync them from the stylesheet.

   The sprite is attached ONLY inside prefers-reduced-motion:
   no-preference. Under reduce, .is-playing therefore keeps the poster
   instead of showing the whole grid shrunk to fit. */

.demo-figure[data-demo="{id}"] {{
  background-image: url("/rig/{id}-poster.webp");
}}

@media (prefers-reduced-motion: no-preference) {{
  .demo-figure[data-demo="{id}"].is-playing {{
    background-image: url("/rig/{id}.webp");
    background-size: {sx}% {sy}%;
    animation: demo-{id} {dur}s steps(1) 1 both;
  }}
}}

@keyframes demo-{id} {{
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("demo_id")
    ap.add_argument("frames_dir")
    ap.add_argument("--duration", type=float, default=4.0)
    ap.add_argument("--quality", type=int, default=82)
    args = ap.parse_args()

    files = sorted(
        f for f in os.listdir(args.frames_dir) if f.startswith("f") and f.endswith(".png")
    )
    if not files:
        sys.exit("no f*.png frames in " + args.frames_dir)
    n = len(files)
    side = int(round(math.sqrt(n)))
    if side * side != n:
        sys.exit("frame count %d is not a perfect square; capture 49/64/81/100" % n)

    first = Image.open(os.path.join(args.frames_dir, files[0]))
    px = first.size[0]
    if first.size[0] != first.size[1]:
        sys.exit("frames must be square, got %s" % (first.size,))
    if side * px > MAX_TEXTURE:
        sys.exit("sheet would be %dpx wide, over the %d texture limit"
                 % (side * px, MAX_TEXTURE))

    sheet = Image.new("RGBA", (side * px, side * px), (0, 0, 0, 0))
    for i, name in enumerate(files):
        im = Image.open(os.path.join(args.frames_dir, name)).convert("RGBA")
        sheet.paste(im, ((i % side) * px, (i // side) * px))

    out_dir = os.path.join(ROOT, "public", "rig")
    os.makedirs(out_dir, exist_ok=True)
    sprite = os.path.join(out_dir, args.demo_id + ".webp")
    poster = os.path.join(out_dir, args.demo_id + "-poster.webp")
    sheet.save(sprite, "WEBP", quality=args.quality, method=6)
    first.convert("RGBA").save(poster, "WEBP", quality=88, method=6)

    step = 100.0 / (side - 1)
    lines = []
    for i in range(n):
        t = 100.0 * i / (n - 1)
        lines.append("  %.4f%% { background-position: %.4f%% %.4f%%; }"
                     % (t, (i % side) * step, (i // side) * step))
    css = HEADER.format(id=args.demo_id, n=n, c=side, r=side, px=px,
                        sx=side * 100, sy=side * 100, dur=("%g" % args.duration))
    css += "\n".join(lines) + "\n}\n"
    css_path = os.path.join(ROOT, "src", "demo-%s.css" % args.demo_id)
    with open(css_path, "w", newline="\n") as f:
        f.write(css)

    print("sprite  %s  %dx%d  %dKB"
          % (os.path.relpath(sprite, ROOT), side * px, side * px,
             os.path.getsize(sprite) // 1024))
    print("poster  %s  %dKB"
          % (os.path.relpath(poster, ROOT), os.path.getsize(poster) // 1024))
    print("css     %s  (%d keyframes, background-size %d%%)"
          % (os.path.relpath(css_path, ROOT), n, side * 100))


if __name__ == "__main__":
    main()
